name: xlsio_example
description: Demo for creating a Excel file using syncfusion_flutter_xlsio package.

environment:
  sdk: ">=2.17.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  open_file: ^3.0.1
  syncfusion_flutter_xlsio:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
