name: syncfusion_pdfviewer_web_example
description: Demonstrates how to use the syncfusion_pdfviewer_web with the help of syncfusion_flutter_pdfviewer plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer
      path: flutter_pdfviewer/syncfusion_flutter_pdfviewer
      branch: release/22.1.1
      ref: release/22.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
