include: package:syncfusion_flutter_core/analysis_options.yaml

analyzer:
  errors:
    include_file_not_found: ignore
    lines_longer_than_80_chars: ignore
    avoid_as: false
    use_raw_strings: ignore
    unnecessary_null_checks: ignore
    noop_primitive_operations: ignore
