include: package:syncfusion_flutter_core/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    library_private_types_in_public_api: ignore
    include_file_not_found: ignore
    avoid_as: ignore
    avoid_dynamic_calls: ignore
