part of pdf;

enum _Asn1UniversalTags {
  reservedBER,
  boolean,
  integer,
  bitString,
  octetString,
  nullValue,
  objectIdentifier,
  objectDescriptor,
  externalValue,
  real,
  enumerated,
  embeddedPDV,
  utf8String,
  relativeOid,
  sequence,
  setValue,
  numericString,
  printableString,
  teletexString,
  videotexString,
  ia5String,
  utfTime,
  generalizedTime,
  graphicsString,
  visibleString,
  generalString,
  universalString,
  characterString,
  bmpString,
  constructed,
  application,
  tagged
}
